title: dsalgo
description: A Package for Data Structures and Algorithms
theme: jekyll-theme-slate
# https://github.com/topics/jekyll-theme
url: https://kagemeka.github.io
lsi: false
safe: true
source: "."
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
