# https://dart.dev/go/core-lints

include: package:lints/recommended.yaml
# Uncomment the following section to specify additional rules.

# information for analyzer and linter.
# https://dart.dev/guides/language/analysis-options
# linter options (error rules)
# https://dart.dev/tools/linter-rules#error-rules

# linter:
#   rules:
#     - camel_case_types

# analyzer:
#   exclude:
#     - path/to/excluded/files/**
