name: dsalgo
description: A package for datastructures and algorithms.
version: 0.0.1
homepage: https://github.com/kagemeka/dsalgo/dart

environment:
  sdk: ">=2.18.7 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
