# https://rust-lang.github.io/rustfmt
array_width = 63
attr_fn_like_width = 63
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 0
brace_style = "SameLineWhere"
chain_width = 63
color = "Auto"
combine_control_expr = true
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 0
error_on_line_overflow = true
error_on_unformatted = true
# fn_args_layout = "Tall"
fn_args_layout = "Compressed"
fn_call_width = 63
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
doc_comment_code_block_with = 80
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Lower"
hide_parse_errors = false
ignore = []
imports_granularity = "Crate"
imports_indent = "Block"
# imports_layout = "HorizontalVertical"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 0
license_template_path = ""
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 80
merge_derives = true
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
report_fixme = "Always"
report_todo = "Always"
required_version = "1.5.1"
single_line_if_else_max_width = 63
skip_children = false
short_array_element_width_threshold = 15
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
struct_lit_width = 63
struct_variant_width = 31
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
version = "Two"
where_single_line = false
wrap_comments = true
