version: '3.9'


services:
  cpp:
    build:
      context: .
      dockerfile: Dockerfile
    image: kagemeka/dsalgo-cpp:latest
    restart: on-failure
    tty: true
    volumes:
      - type: bind
        source: $ROOT
        target: /root/$PROJECT
        volume:
          nocopy: true
        read_only: false
    working_dir: /root/$PROJECT
