name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: CI
        run: |
          cd src/rust
          ./scripts/rust_ci.sh
      - name: Build
        run: |
          cd src/rust
          cargo build --verbose
      - name: Run tests
        run: |
          cd src/rust
          cargo test --verbose
